spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/TodoProjectRepo
  application:
    name: todoproject-todo-temp

server:
    port: 5000
    
eureka:
  instance:
    instance-id: todoproject-todo-temp
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.35.45:8761/eureka/
      enabled: true
            
            
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    shutdown:
#      enabled: true
#    health:
#      show-details: ALWAYS