spring:
  application:
    name: service-b
server:
    port: 8900
eureka:
  instance:
    instance-id: service-b-inst001
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      enabled: true
            
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    shutdown:
#      enabled: true
#    health:
#      show-details: ALWAYS